# Generated by Django 4.2.13 on 2024-06-18 18:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=50)),
                ('balance', models.FloatField(default=0)),
                ('blocking_time', models.DateTimeField(blank=True, null=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'account',
                'verbose_name_plural': 'accounts',
                'db_table': 'services_accounts',
            },
        ),
        migrations.CreateModel(
            name='StatusAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=255, unique=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'status_user',
                'verbose_name_plural': 'status_users',
                'db_table': 'services_status_account',
            },
        ),
        migrations.CreateModel(
            name='StatusCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=255, unique=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'status_card',
                'verbose_name_plural': 'status_cards',
                'db_table': 'services_status_cards',
            },
        ),
        migrations.CreateModel(
            name='StatusPos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=255, unique=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'status_pos',
                'verbose_name_plural': 'status_pos',
                'db_table': 'services_status_pos',
            },
        ),
        migrations.CreateModel(
            name='TypeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=255, unique=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'type_account',
                'verbose_name_plural': 'type_accounts',
                'db_table': 'services_type_account',
            },
        ),
        migrations.CreateModel(
            name='TypeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=255, unique=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'type_card',
                'verbose_name_plural': 'type_cards',
                'db_table': 'services_type_cards',
            },
        ),
        migrations.CreateModel(
            name='TypePos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=255, unique=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'pos',
                'verbose_name_plural': 'pos',
                'db_table': 'services_type_pos',
            },
        ),
        migrations.CreateModel(
            name='Pos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_sale_number', models.CharField(max_length=20, unique=True)),
                ('blocking_time', models.DateTimeField(blank=True, null=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='services.account', verbose_name='account_id')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='services.statuspos', verbose_name='status_id')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='services.typepos', verbose_name='type_id')),
            ],
            options={
                'verbose_name': 'status_pos',
                'verbose_name_plural': 'status_pos',
                'db_table': 'services_pos',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=20, unique=True)),
                ('ref', models.CharField(max_length=30, unique=True)),
                ('password_card', models.CharField(max_length=6)),
                ('date_due_password', models.DateTimeField(default=datetime.datetime(2024, 12, 18, 18, 50, 26, 927555))),
                ('blocking_time', models.DateTimeField(blank=True, null=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='services.account', verbose_name='account_id')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='services.statuscard', verbose_name='status_id')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='services.typecard', verbose_name='type_id')),
            ],
            options={
                'verbose_name': 'card',
                'verbose_name_plural': 'cards',
                'db_table': 'services_cards',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='services.statusaccount', verbose_name='status_id'),
        ),
        migrations.AddField(
            model_name='account',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='services.typeaccount', verbose_name='type_id'),
        ),
        migrations.AddField(
            model_name='account',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customers.user', verbose_name='user_id'),
        ),
    ]
