# Generated by Django 4.2.13 on 2024-06-17 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='date_due_password',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 17, 18, 0, 38, 143870)),
        ),
    ]
