# Generated by Django 4.2.13 on 2024-06-18 19:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_user_date_due_password_alter_user_status_id_and_more'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status_id',
            field=models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.DO_NOTHING, to='services.statusaccount'),
        ),
        migrations.AlterField(
            model_name='account',
            name='type_id',
            field=models.ForeignKey(db_column='type_id', on_delete=django.db.models.deletion.DO_NOTHING, to='services.typeaccount'),
        ),
        migrations.AlterField(
            model_name='account',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to='customers.user'),
        ),
        migrations.AlterField(
            model_name='card',
            name='account_id',
            field=models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.DO_NOTHING, to='services.account'),
        ),
        migrations.AlterField(
            model_name='card',
            name='date_due_password',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 18, 19, 0, 21, 967363)),
        ),
        migrations.AlterField(
            model_name='card',
            name='status_id',
            field=models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.DO_NOTHING, to='services.statuscard'),
        ),
        migrations.AlterField(
            model_name='card',
            name='type_id',
            field=models.ForeignKey(db_column='type_id', on_delete=django.db.models.deletion.DO_NOTHING, to='services.typecard'),
        ),
        migrations.AlterField(
            model_name='pos',
            name='account_id',
            field=models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.DO_NOTHING, to='services.account'),
        ),
        migrations.AlterField(
            model_name='pos',
            name='status_id',
            field=models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.DO_NOTHING, to='services.statuspos'),
        ),
        migrations.AlterField(
            model_name='pos',
            name='type_id',
            field=models.ForeignKey(db_column='type_id', on_delete=django.db.models.deletion.DO_NOTHING, to='services.typepos'),
        ),
    ]
