# Generated by Django 4.2.13 on 2024-06-18 19:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_due_password',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 18, 19, 0, 21, 964617)),
        ),
        migrations.AlterField(
            model_name='user',
            name='status_id',
            field=models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.DO_NOTHING, to='customers.statususer'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type_id',
            field=models.ForeignKey(db_column='type_id', on_delete=django.db.models.deletion.DO_NOTHING, to='customers.typeuser'),
        ),
    ]
