# Generated by Django 4.2.13 on 2024-06-17 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_due_password',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 17, 18, 0, 38, 141051)),
        ),
        migrations.AlterModelTable(
            name='statususer',
            table='customers_status_users',
        ),
        migrations.AlterModelTable(
            name='typeuser',
            table='customers_type_users',
        ),
        migrations.AlterModelTable(
            name='user',
            table='customers_users',
        ),
    ]
